<?php

namespace Potager\BusinessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FightRepository extends EntityRepository
{
}
