<?php

namespace Potager\BusinessBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	
	public function getNearbyPlayerQuery($faction, $level, $diffLevel)
	{
		$qb = $this->createQueryBuilder('u')
			->join('u.attribute', 'a')
			->where('u.faction != :faction')
			->andWhere('a.level >= :level1')
			->andWhere('a.level <= :level2')
			->setParameter('faction', $faction)
			->setParameter('level1', $level - $diffLevel )
			->setParameter('level2', $level + $diffLevel );
		
		return $qb;
	}
}
